Improvements on translation system and command handler
Hint-Box/FakeOS pull request #6
Opened 2021-03-25 21:02 UTC by fabiopolancoe

Updates on translation system and command handling were made, added an install script for Linux (Sebas, please make the installation script for Windows based on mine).

2021-03-25 21:30 UTC, FRostri reviewed
En la linea 128 hay un sangrado de más

2021-03-25 21:43 UTC, fabiopolancoe commented
> En la linea 128 hay un sangrado de más

Gracias

2021-03-26 02:48 UTC, Sebastian-byte requested changes
You must add newline at the end of the files for compatiblity purposes.

2021-03-26 02:53 UTC, Sebastian-byte commented
Con solo abrir los archivos que GitHub te dice que no tiene una nueva línea al final de los archivos y guardar se debería solucionar.

2021-03-26 03:04 UTC, merged